name: fashion-atlas
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - ultralytics
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - flask
  - pip:
    - tensorboard