path: C:\Users\troyd\Programs\ECE379K\fashion-atlas\data\DeepFashion2Yolo
train: C:\Users\troyd\Programs\ECE379K\fashion-atlas\data\DeepFashion2Yolo\images\train
val: C:\Users\troyd\Programs\ECE379K\fashion-atlas\data\DeepFashion2Yolo\images\val

names:
  0: Short Sleeve Top
  1: Long Sleeve Top
  2: Short Sleeve Outwear
  3: Long Sleeve Outwear
  4: Vest
  5: Sling
  6: Shorts
  7: Trousers
  8: Skirt
  9: Short Sleeve Dress
  10: Long Sleeve Dress
  11: Vest Dress
  12: Sling Dress