model:
  embedding_dim: 1024
  expander_dim: 4096

train:
  epochs: 10
  batch_size: 60
  run_name: 'ConvNeXt-T Decaying Semi-Hard Transforms'

optimizer:
  lr: 0.0001
  weight_decay: 0.001

scheduler:
  warmup_steps: 2
  period: 20
  max_lr: 0.0001

loss:
  margin: 1.5
  initial_temperature: 10.0
  temperature_decay: 0.995
  minimum_temperature: 0.1
  triplet_weight: 5.0
  vicreg_weight: 0.8
  var_coeff: 1.0
  inv_coeff: 1.0
  cov_coeff: 0.00001