model:
  embedding_dim: 1000
  expander_dim: 4000

train:
  epochs: 20
  batch_size: 17
  run_name: 'ConvNeXt-B'

optimizer:
  lr: 0.00001
  weight_decay: 0.0001

loss:
  margin: 1.9
  triplet_weight: 5.0
  vicreg_weight: 1.0
  var_coeff: 1.0
  inv_coeff: 1.0
  cov_coeff: 0.00001